<div class="page-content">
    <div class="container">
        <table class="table table-striped table-bordered">
            <thead>
                <tr class="text-center">
                    <th class="text-center">Código</th>
                    <th class="text-center">Título</th>
                    <th class="text-center">Opções</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->listaNewsletter as $news): ?>
                    <tr>
                        <td class="col-md-1 text-center"><label><?= str_pad($news->getId(),6,0,STR_PAD_LEFT) ?></label></td>
                        <td class="col-md-8"><label><?= $news->getTitulo() ?></label></td>
                        <td class="text-center"><a href="<?=$this->baseUrl("/newsletter/visualizar/id/{$news->getId()}")?>" class="btn btn-primary">Ver newsletter</a></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>  