<div class="page-content">
    <div class="container">
        <form class="form-horizontal" action="<?=$this->baseUrl('/newsletter/enviar')?>">
            <table class="table table-striped table-bordered">
                <legend class="text-center"><?= $this->newsletter->getTitulo() ?></legend>
                <tbody>
                    <?php foreach ($this->newsletter->getNoticias() as $noticia): ?>
                        <tr class="text-center">
                            <td>
                                <b><h3><?= $noticia->getTitulo() ?></h3></b>
                            </td>
                        </tr>
                        <tr class="small">
                            <td>
                                Em <?= date("d/m/Y", strtotime($noticia->getDataPublicacao())) ?> 
                                <div class="pull-right">
                                    <a target="_blank" href="<?= $noticia->getLink() ?>">
                                        Saiba mais <i class="fa fa-external-link"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <tr class="text-muted">
                            <td style="vertical-align: middle">
                                <i>por 
                                    <?php if (!empty($noticia->getAutor())): ?>
                                        <?= $noticia->getAutor() ?>, 
                                    <?php endif; ?>
                                    <?= $noticia->getMedia() ?>
                                </i> 
                                <div class="pull-right small" style="vertical-align: middle">
                                    <?php foreach ($noticia->getCategorias() as $i => $categoria): ?>
                                        <?= $i > 0 ? "| " : "" ?>
                                        <?= $categoria ?>
                                    <?php endforeach; ?>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="small"></div>
                                <?= $noticia->getDescricao() ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
                <tfoot>
                    <tr>
                        <td>
                            <label class="control-label col-sm-2 ">Enviar para</label>
                            <div class="col-sm-8">
                                <input type="email" class="form-control" />
                            </div>
                            <div class="col-sm-2">
                                <button type="submit" class="btn btn-sm btn-primary form-control">Enviar</button>
                            </div>
                        </td>
                    </tr>
                </tfoot>
            </table>
        </form>
    </div>
</div>  