<?= $this->doctype() . PHP_EOL ?>
<html lang="pt-br">
    <head>
        <?= $this->headTitle("PRNews - TAbreu")->setSeparator(' | ') . PHP_EOL ?>
        <?= $this->headMeta() . PHP_EOL ?>
        <?= $this->headLink() . PHP_EOL ?>
        <?= $this->headScript() . PHP_EOL ?>
    </head>

    <body>
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <ul class="nav navbar-nav">
                        <li ><a  href="<?=$this->baseUrl()?>">Seleção de notícias</a></li>
                        <li ><a  href="<?=$this->baseUrl("/newsletter/lista")?>">Newsletters cadastradas</a></li>
                    </ul>
                </div>
            </div>
        </nav> 
        <br><br>
        <?php echo $this->layout()->content . PHP_EOL ?>
    </body>
</html>

